server:
  port: 2222
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # 超时时间 单位：毫秒
    timeout: 5000
    password: 123456
    jedis:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 1
        # 最大等待时间，单位：毫秒
        max-wait: 3000
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/translate?characterEncoding=utf-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000